### ISSUE TITLE
SDK is broken: trying to get KV value throws exception

### ISSUE THREAD

**Issue by martinbean** [cloudflare/cloudflare-php#152]
When trying to retrieve the value of a key–value pair using the `Cloudflare\API\Endpoints\WorkersKV::getAllKeysAndValuesForNamespace` method, the SDK throws a `JSONException` because the response of that call (https://api.cloudflare.com/#workers-kv-namespace-read-key-value-pair) is just plain text, and not JSON as the SDK is naïvely assuming all responses are. However, the API _does_ return `application/json` as the `Content-Type`.

The API either needs to return an appropriate content type for responses, or the SDK needs to accommodate plain text responses like this.

**Comment by dumityty** [comment]
Just ran into the same issue when I start using the code in PR #139 to use the WorkerKV endpoints.
It looks like the issue is with the Guzzle adapter in the checkError method (\Cloudflare\API\Adapter\Guzzle::checkError) where the response is always assumed to be JSON, though looks like very few endpoints can return plain text values now:

```
private function checkError(ResponseInterface $response)
    {
        $json = json_decode($response->getBody());
...
```
